/**
 * One-time codemod: rewrites every internal URL from the 2026-07 rebuild's
 * scheme to the restored one in src/data/url-map.js.
 *
 * There are ~3,100 such links across hand-authored pages, generated pages and
 * the generator templates themselves, plus canonical tags, og:url, twitter:
 * URLs, JSON-LD @id/url values, public/llms.txt, and prose in
 * src/data/geo-aeo.js that names calculator URLs inside FAQ answers. Hand
 * editing that is how a canonical ends up pointing at a redirect, so this
 * rewrites all of them from the map in one pass.
 *
 *   node scripts/rewrite-urls.mjs --dry-run    # report only
 *   node scripts/rewrite-urls.mjs              # apply
 *
 * SELF-EXCLUSION (learned the hard way): the map file and this script are
 * skipped. Both contain the old URLs as data, and rewriting them turned the
 * map's keys into copies of their own values, silently disarming it.
 *
 * dist/ is skipped too — it is build output, regenerated by `npm run build`.
 */
import fs from 'node:fs'
import path from 'node:path'
import { MOVED_URLS, SITE_ORIGIN } from '../src/data/url-map.js'

const root = path.resolve(import.meta.dirname, '..')
const dryRun = process.argv.includes('--dry-run')

const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', '.wrangler', 'api', 'migration', 'docs', 'images'])
const SKIP_FILES = new Set([
  path.join(root, 'src', 'data', 'url-map.js'),
  path.join(root, 'scripts', 'rewrite-urls.mjs'),
])
const EXTENSIONS = new Set(['.html', '.mjs', '.js', '.txt', '.xml'])

// Longest first, so the trailing-slash form is replaced before the bare one.
const moves = Object.entries(MOVED_URLS)
  .filter(([from, to]) => from !== to)
  .sort(([a], [b]) => b.length - a.length)

if (!moves.length) {
  console.error('rewrite-urls: MOVED_URLS has no old -> new pairs. Check src/data/url-map.js.')
  process.exit(1)
}

/**
 * Each old URL is replaced only where it is unambiguously a whole URL: inside
 * quotes, at the end of an absolute URL, or followed by # or ?. A bare
 * substring replacement would corrupt longer paths that merely start the same
 * way (/garages vs /calculator/garages.html).
 */
function rewrite(text) {
  let out = text
  let count = 0
  for (const [from, to] of moves) {
    const bare = from.replace(/\/$/, '')
    const patterns = [
      [new RegExp(`(href=["'])${escape(from)}(["'#?])`, 'g'), `$1${to}$2`],
      [new RegExp(`${escape(SITE_ORIGIN)}${escape(from)}(["'#?\\s<])`, 'g'), `${SITE_ORIGIN}${to}$1`],
      [new RegExp(`burchcontracting\\.com${escape(from)}(["'#?\\s.,)<]|$)`, 'g'), `burchcontracting.com${to}$1`],
      [new RegExp(`(["'])${escape(from)}(["'])`, 'g'), `$1${to}$2`],
    ]
    if (bare !== from) {
      patterns.push([new RegExp(`(href=["'])${escape(bare)}(["'#?])`, 'g'), `$1${to}$2`])
    }
    for (const [pattern, replacement] of patterns) {
      out = out.replace(pattern, (...args) => {
        count++
        return replacement.replace(/\$(\d)/g, (_, n) => args[Number(n)] ?? '')
      })
    }
  }
  return { out, count }
}

function escape(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full, files)
    else if (EXTENSIONS.has(path.extname(entry.name)) && !SKIP_FILES.has(full)) files.push(full)
  }
  return files
}

let changedFiles = 0
let totalReplacements = 0
const report = []

for (const file of walk(root)) {
  const before = fs.readFileSync(file, 'utf8')
  const { out, count } = rewrite(before)
  if (out === before) continue
  changedFiles++
  totalReplacements += count
  report.push(`  ${String(count).padStart(5)}  ${path.relative(root, file).split(path.sep).join('/')}`)
  if (!dryRun) fs.writeFileSync(file, out)
}

console.log(`rewrite-urls: ${totalReplacements} replacement(s) across ${changedFiles} file(s)${dryRun ? ' (dry run — nothing written)' : ''}`)
console.log(report.sort((a, b) => Number(b.trim().split(/\s+/)[0]) - Number(a.trim().split(/\s+/)[0])).slice(0, 30).join('\n'))
if (report.length > 30) console.log(`  … and ${report.length - 30} more file(s)`)
